### ISSUE TITLE
dynamic language formatting using `@content`

### ISSUE THREAD

**Issue by thenbe** [LostNeophyte/null-ls-embedded#10]
Hi. After experimenting with it for a bit, I managed to get syntax highlighting to work based on the language name specified in the comment. However, formatting only works when I hardcode the language name in the `injections.scm` file. Is there to get formatting to work without doing that?

To illustrate, here are two methods the are close to what I'm trying to achieve, but not quiet there:

## Examples

> Queries were placed in: `nvim/queries/ecma/injections.scm`.
> Testing was done against this `typescript` file:
> 
> ```typescript
> const myhtml = /* html */ ` <html> <body></body> </html> `;
> const mysql = /* sql */ `SELECT * FROM foo`;
> 
> const foo = `bar`;
> ```

### Method 1. Hardcoding the language name: `@html`

- Syntax highlighting: YES (but hardcoded to html)
- Formatting: YES
- However this will match _every_ template string in the file (i.e. any string surrounded with angled brackets eg. const foo = \`bar\`)

```query
; extends

; /* html */ `<html>`
(variable_declarator
	(template_string) @html (#offset! @html 0 1 0 -1)
	)
```

### Method 2. Dynamic language name based on the preceding comment

- Syntax highlighting: YES (dynamic)
- Formatting: NO

```query
; extends

; /* html */ `<html>`
; /* sql */ `SELECT * FROM foo`
(variable_declarator
  (comment) @language (#offset! @language 0 3 0 -3)
  (template_string) @content (#offset! @content 0 1 0 -1)
  )

```

---

Is there a way to get formatting to work in method 2? I couldn't figure out why syntax highlighting was working OK in both methods, but formatting would only work in method 1.

**Comment by LostInTheLogs** [comment]
thanks for the detailed issue, is the problem fixed in the `refactor/simplify-getting-injections` branch?

**Comment by thenbe** [comment]
It is! Thank you.
