### ISSUE TITLE
How to work with vue, svelte, html?

### ISSUE THREAD

**Issue by Wansmer** [LostNeophyte/null-ls-embedded#2]
Hi! Cool plugin!
I try to use it with `vue` (embedded `scss`), but plugin not format it (with both providing command).
I check [vue/injections.scm](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/vue/injections.scm) in treesitter-nvim - `scss` present.
Maybe I do something wrong? Can you show, how can I configured plugin for using with `vue`, `svelte`, `html` e.t.c? Thanks!

**Comment by LostInTheLogs** [comment]
I don't know any vue, can you send a code snippet, I'll see what's wrong

**Comment by Wansmer** [comment]
No formatted:
```vue
<script setup>
const test = {
one: 'one',
};
</script>

<style lang="scss">
.test{
display: inline;
}
</style>
```
Expected:
```vue
<script setup>
const test = {
  one: 'one',
};
</script>

<style lang="scss">
.test {
  display: inline;
}
</style>
```

null-ls (maybe help):
```lua
null_ls.setup({
  on_attach = require('config.lsp.default').on_attach,
  debug = false,
  sources = {
    -- js, ts
    diagnostics.eslint_d,
    code_actions.eslint_d,
    formatting.eslint_d,

    -- lua
    formatting.stylua,

    -- css/sass/scss etc
    diagnostics.stylelint,
    formatting.stylelint,

    -- markdown
    formatting.markdownlint,
  },
})
```

Btw, same code successful formatting in markdown

**Comment by LostInTheLogs** [comment]
does css formatting work in markdown?

**Comment by Wansmer** [comment]
> does css formatting work in markdown?

Yes

**Comment by LostInTheLogs** [comment]
do you have a `stylelint` config file you could share?

**Comment by Wansmer** [comment]
Clarification: formatted in md when it separate blocks:
```scss
.test {
  display: inline;
}
```

```javascript
const test = {
  one: 'one',
};
```

Stylelint rc:
```javascript
/* eslint-env node */
module.exports = {
  'extends': [
    'stylelint-config-standard-scss',
    'stylelint-config-standard-vue/scss',
  ],
  'overrides': [
    {
      'files': [ '*.vue', '**/*.vue' ],
      'rules': {
        'string-quotes': 'double',
        'max-nesting-depth': 3,
        'declaration-block-no-duplicate-properties': true,
      },
    },
  ],
  'rules': {
    'max-nesting-depth': 3,
    'declaration-block-no-duplicate-properties': true,
    'string-quotes': 'double',
  },
};
```

**Comment by LostInTheLogs** [comment]
does it work with this null-ls config?
```lua
sources = {
  formatting.stylelint.with {args = { "--fix", "--stdin"} 
}

**Comment by LostInTheLogs** [comment]
I think you just found something that I thought I wouldn't need to deal with: some formatters may need an actual file.
the default args are `{ "--fix", "--stdin", "--stdin-filename", "$FILENAME" }` the filename will be substituted for `file.vue` and not `file.(s)css` and `your_file` doesn't like it. the plugin would need to create a temporary file and run the formatter on that file, it would be possible to also have LSP formatting and maybe diagnosctics and completion with that solution(the server would probably need single file support), I'm not sure if that's a good solution though, I'd somehow need to make sure that the file always gets deleted, unless I create the file in /tmp but then there's cross-platform support and not every formatter will work with that either

**Comment by Wansmer** [comment]
> does it work with this null-ls config?
> 
> ```lua
> sources = {
>   formatting.stylelint.with {args = { "--fix", "--stdin"} 
> }
> ```

Now, `scss` is formatting, `js` still no formatted (with additional args too). When formatter is `eslint_d` – adds blank line. When just `eslint` – not adds blank line.

I am not sure, but some formatters, as I know, work with file just like string (get string – return string) and it no necessary to create tmp file or buffer.

**Comment by Wansmer** [comment]
I also tested <style> and <script> tags in html - plugin works, but set text in no correct place and no correct indents:
Before:
<img width="258" alt="Снимок экрана 2022-12-02 в 19 49 51" src="https://user-images.githubusercontent.com/46977173/205343834-e337d270-a98c-4762-8829-2156a868b23b.png">
After:
<img width="250" alt="Снимок экрана 2022-12-02 в 19 50 02" src="https://user-images.githubusercontent.com/46977173/205343873-558ea860-d1cd-4857-a455-41156c08ce07.png">

I hope, it will work in the future

**Comment by LostInTheLogs** [comment]
I think `eslint` needs a file unfortunately, otherwise it doesn't seem to format and just outputs the input.

I'll try to fix <style> and <script>

**Comment by LostInTheLogs** [comment]
> I also tested <style> and <script> tags in html - plugin works, but set text in no correct place and no correct indents: Before: <img alt="Снимок экрана 2022-12-02 в 19 49 51" width="258" src="https://user-images.githubusercontent.com/46977173/205343834-e337d270-a98c-4762-8829-2156a868b23b.png"> After: <img alt="Снимок экрана 2022-12-02 в 19 50 02" width="250" src="https://user-images.githubusercontent.com/46977173/205343873-558ea860-d1cd-4857-a455-41156c08ce07.png">
> 
> I hope, it will work in the future

It should work now, and blank likes won't be added as well

**Comment by Wansmer** [comment]
Unfortunately, still break indents.
Also, null-ls reporting about error (test on html and vue - same error)
<img width="1605" alt="Снимок экрана 2022-12-02 в 20 34 54" src="https://user-images.githubusercontent.com/46977173/205352307-132c8293-1f81-44b7-b7b6-d3fc023816b8.png">

**Comment by LostInTheLogs** [comment]
what formatter are you using? and paste the full html file here

**Comment by Wansmer** [comment]
For html - buitin lsp formatter (html-lsp), for css - stylelint, for js - eslint.
File before using plugin:
```html
<!DOCTYPE html>
<html lang="en">

<head>
  <title></title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="css/style.css" rel="stylesheet">
  <style>
    .test {
      display: flex;
    }
  </style>
</head>

<body>

  <script>
    let obj = {
      one: 'one'
    }
  </script>
</body>

</html>
```
After:
```html
<!DOCTYPE html>
<html lang="en">

<head>
  <title></title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="css/style.css" rel="stylesheet">
  <style>
    .test {
      display: flex;
    }</style>
</head>

<body>

  <script>
    let obj = {
          one: 'one'
        }
      </script>
</body>

</html>
```

**Comment by LostInTheLogs** [comment]
<style> should work now

**Comment by Wansmer** [comment]
> <style> should work now

Yes, <style> work, great!

**Comment by LostInTheLogs** [comment]
now <script> should work better (it probably won't touch anything)

**Comment by Wansmer** [comment]
In html work, thanks

**Comment by LostInTheLogs** [comment]
with this `.eslintrc` <script> is formatted in vue 
```json
{
    "extends": "eslint:recommended",
    "rules": {
        "indent": [
            1,
            4
        ],
    },
    "parserOptions": {
        "ecmaVersion": "latest"
    },
    "env": {
        "es6": true
    }
}
```

**Comment by LostInTheLogs** [comment]
now both <script> and <style> should work in vue with default null-ls builtins

**Comment by Wansmer** [comment]
Hm, I tried to test with your  `.eslintrc` – it not work for me. 
Also, I tested with variants:
```lua
    formatting.eslint, -- no work
    formatting.eslint.with({ args = { '--fix-dry-run', '--stdin' } }), -- no work
    formatting.eslint.with({ args = { '--fix', '--stdin' } }), -- no work
    formatting.eslint.with({ args = { '--fix-dry-run' } }), -- no work
    formatting.eslint.with({ args = { '--fix'  } }), -- no work
```
And the blank line is present again.

https://user-images.githubusercontent.com/46977173/205432315-17540341-c24d-4b2f-b6f7-fc4fbbc16dfa.mov

**Comment by Wansmer** [comment]
> now both <script> and <style> should work in vue with default null-ls builtins

With last commit and with `formatting.eslint` without args now works! Thanks!

**Comment by LostInTheLogs** [comment]
I checked eslint_d, will try eslint

**Comment by Wansmer** [comment]
> I checked eslint_d, will try eslint

I checked both (eslint_d and eslint) - work

**Comment by LostInTheLogs** [comment]
great, is anything left or is the issue fixed?

**Comment by Wansmer** [comment]
Fixed! I have one suggestion for a new feature. Later I to open new issue for it.
