### ISSUE TITLE
`ignore_langs` list is not updatable

### ISSUE THREAD

**Issue by Wansmer** [LostNeophyte/null-ls-embedded#6]
According [README](https://github.com/LostNeophyte/null-ls-embedded#stop-some-embedded-languages-from-being-formatted) I try to edit `ignore_langs`, but `ignore_langs` is not updated: 
1. Using with `config` section in 'packer` – not work (because reference already on other table);
```lua
  use({
    'LostNeophyte/null-ls-embedded',
    config = function()
      require('null-ls-embedded').ignore_langs = {
        ['*'] = { 'comment', 'vim' }, -- don't format `comment` in all languages
        markdown = { 'inline_markdown' }, -- don't format embedded `inline_markdown` in `markdown` files
      }
    end,
  })
```
2. Using with `setup` section in 'packer` – throws error (because plugin not exist yet);
```lua
  use({
    'LostNeophyte/null-ls-embedded',
    setup = function()
      require('null-ls-embedded').ignore_langs = {
        ['*'] = { 'comment', 'vim' }, -- don't format `comment` in all languages
        markdown = { 'inline_markdown' }, -- don't format embedded `inline_markdown` in `markdown` files
      }
    end,
  })
```
3. Just put code from readme to init.lua - also not work

Please, add `setup` function for setting (similar as in most other plugins).

**Comment by LostInTheLogs** [comment]
it should be `require('null-ls-embedded').config.ignore_langs`

**Comment by LostInTheLogs** [comment]
the readme is wrong

**Comment by Wansmer** [comment]
Yes, that work.

**Comment by LostInTheLogs** [comment]
I'll add a config function though, I'm doing a bigger refactor
