### ISSUE TITLE
Add support for Quarto

### ISSUE THREAD

**Issue by igorlfs** [LostNeophyte/null-ls-embedded#9]
Hey, nice plugin!

I noticed [quarto](https://quarto.org/) isn't enabled as one of the default filetypes. I tried adding it, but I got an error:

```
null-ls-embedded/lua/null-ls-embedded/utils.lua:203: attempt to index local 'query' (a nil value)
```

Quarto is pretty much markdown, it doesn't have its own parser

**Comment by LostInTheLogs** [comment]
The plugin requires a treesitter parser, but it shouldn't error when there are no queries, I'll fix that
